import { AIInsight, AISuggestion, AISummary } from '@/features/ai/types'

export async function analyzeHistory(_data: { workOrders: unknown[]; equipments: unknown[]; maintenances: unknown[] }): Promise<AIInsight[]> {
  await new Promise(r => setTimeout(r, 1000))
  const insights: AIInsight[] = [
    {
      id: 'insight-1',
      type: 'recurring_failure',
      title: 'Falha recorrente detectada',
      description: 'O Motor Trifásico apresentou 3 falhas similares nos últimos 30 dias.',
      confidence: 0.92,
      affectedIds: ['1'],
      createdAt: new Date().toISOString(),
    },
    {
      id: 'insight-2',
      type: 'maintenance_suggestion',
      title: 'Manutenção preventiva sugerida',
      description: 'Com base no histórico, recomendamos revisão do compressor em até 7 dias.',
      confidence: 0.85,
      affectedIds: ['2'],
      createdAt: new Date().toISOString(),
    },
  ]
  return insights
}

export async function detectRecurringFailures(_workOrders: unknown[]): Promise<AIInsight[]> {
  await new Promise(r => setTimeout(r, 800))
  return [
    {
      id: 'insight-3',
      type: 'recurring_failure',
      title: 'Padrão de falha recorrente',
      description: 'Detectamos que bombas hidráulicas do setor sul tem parado em média a cada 15 dias.',
      confidence: 0.88,
      affectedIds: ['3'],
      createdAt: new Date().toISOString(),
    },
  ]
}

export async function suggestMaintenance(_equipmentId: string, _history: unknown[]): Promise<AISuggestion> {
  await new Promise(r => setTimeout(r, 1200))
  return {
    id: 'suggestion-1',
    insightId: 'insight-2',
    title: 'Troca de filtro de ar recomendada',
    description: 'O filtro de ar do compressor está com vida útil estimada em 5 dias.',
    proposedAction: { type: 'preventive_maintenance', priority: 'medium', estimatedHours: 2 },
    risk: 'low',
    createdAt: new Date().toISOString(),
  }
}

export async function generateWorkOrderSummary(_workOrder: unknown): Promise<AISummary> {
  await new Promise(r => setTimeout(r, 1000))
  return {
    workOrderId: 'wo-1',
    summary: 'Ordem de serviço para manutenção corretiva no Motor Trifásico, com substituição de rolamentos e alinhamento.',
    keyPoints: ['Falha identificada: ruído excessivo', 'Peças substituídas: 2 rolamentos', 'Tempo de parada: 4h'],
    risks: ['Possível desgaste prematuro se alinhamento não for verificado'],
    nextSteps: ['Acompanhar operação nas próximas 48h', 'Agendar preventiva em 30 dias'],
  }
}

export async function autoGenerateDescription(_title: string, _category: string): Promise<string> {
  await new Promise(r => setTimeout(r, 600))
  return `Manutenção ${_category} executada conforme planejamento. Equipamento inspecionado, lubrificado e testado.`
}

export async function assistPlanning(_constraints: unknown): Promise<Record<string, unknown>> {
  await new Promise(r => setTimeout(r, 1400))
  return {
    suggestion: 'Recomendamos alocar 2 técnicos na segunda-feira para as preventivas pendentes.',
    conflicts: [],
    optimizedSchedule: {},
  }
}
