import { useState, useCallback } from 'react'
import { AIInsight, AISuggestion, AIChatMessage, AISummary } from '@/features/ai/types'
import { analyzeHistory, detectRecurringFailures, suggestMaintenance, generateWorkOrderSummary, autoGenerateDescription, assistPlanning } from '@/features/ai/services/aiService'
import { toast } from 'sonner'

export function useAI() {
  const [insights, setInsights] = useState<AIInsight[]>([])
  const [suggestions, setSuggestions] = useState<AISuggestion[]>([])
  const [chatMessages, setChatMessages] = useState<AIChatMessage[]>([])
  const [isLoading, setIsLoading] = useState(false)

  const runAnalysis = useCallback(async () => {
    setIsLoading(true)
    try {
      const historyInsights = await analyzeHistory({ workOrders: [], equipments: [], maintenances: [] })
      setInsights(prev => [...prev, ...historyInsights])
      toast.success('Análise concluída')
    } catch {
      toast.error('Erro ao analisar histórico')
    } finally {
      setIsLoading(false)
    }
  }, [])

  const detectFailures = useCallback(async () => {
    setIsLoading(true)
    try {
      const failureInsights = await detectRecurringFailures([])
      setInsights(prev => [...prev, ...failureInsights])
      toast.success('Falhas recorrentes detectadas')
    } catch {
      toast.error('Erro ao detectar falhas')
    } finally {
      setIsLoading(false)
    }
  }, [])

  const getMaintenanceSuggestion = useCallback(async (equipmentId: string) => {
    setIsLoading(true)
    try {
      const suggestion = await suggestMaintenance(equipmentId, [])
      setSuggestions(prev => [...prev, suggestion])
      toast.success('Sugestão de manutenção gerada')
      return suggestion
    } catch {
      toast.error('Erro ao gerar sugestão')
      return null
    } finally {
      setIsLoading(false)
    }
  }, [])

  const summarizeWorkOrder = useCallback(async (workOrder: unknown): Promise<AISummary | null> => {
    setIsLoading(true)
    try {
      const summary = await generateWorkOrderSummary(workOrder)
      toast.success('Resumo gerado')
      return summary
    } catch {
      toast.error('Erro ao gerar resumo')
      return null
    } finally {
      setIsLoading(false)
    }
  }, [])

  const generateDescription = useCallback(async (title: string, category: string): Promise<string | null> => {
    setIsLoading(true)
    try {
      const description = await autoGenerateDescription(title, category)
      toast.success('Descrição gerada')
      return description
    } catch {
      toast.error('Erro ao gerar descrição')
      return null
    } finally {
      setIsLoading(false)
    }
  }, [])

  const helpPlanning = useCallback(async () => {
    setIsLoading(true)
    try {
      const plan = await assistPlanning({})
      toast.success('Sugestão de planejamento pronta')
      return plan
    } catch {
      toast.error('Erro ao auxiliar planejamento')
      return null
    } finally {
      setIsLoading(false)
    }
  }, [])

  const sendChatMessage = useCallback(async (message: string) => {
    const userMsg: AIChatMessage = {
      id: `chat-${Date.now()}`,
      role: 'user',
      content: message,
      timestamp: new Date().toISOString(),
    }
    setChatMessages(prev => [...prev, userMsg])

    await new Promise(r => setTimeout(r, 1000))
    const assistantMsg: AIChatMessage = {
      id: `chat-${Date.now()}-assistant`,
      role: 'assistant',
      content: 'Esta é uma resposta simulada do assistente. Em produção, aqui seria a resposta da IA baseada no contexto da manutenção.',
      timestamp: new Date().toISOString(),
    }
    setChatMessages(prev => [...prev, assistantMsg])
  }, [])

  const clearInsights = useCallback(() => setInsights([]), [])
  const clearSuggestions = useCallback(() => setSuggestions([]), [])
  const clearChat = useCallback(() => setChatMessages([]), [])

  return {
    insights,
    suggestions,
    chatMessages,
    isLoading,
    runAnalysis,
    detectFailures,
    getMaintenanceSuggestion,
    summarizeWorkOrder,
    generateDescription,
    helpPlanning,
    sendChatMessage,
    clearInsights,
    clearSuggestions,
    clearChat,
  }
}
